---

- name: Some packages are excluded from updates
  lineinfile:
    path: /etc/yum.conf
    line: 'exclude={{ yum_exclude_packages | join(" ") }}'
    state: present
    regexp: '^exclude='
    insertafter: '[main]'
  when:
    - yum_exclude_packages is defined

- name: Include all packages
  lineinfile:
    path: /etc/yum.conf
    state: absent
    regexp: 'exclude='
  when:
    - yum_exclude_packages is not defined

- name: Execute yum update
  yum:
    name: '*'
    state: latest
    security: '{{ security_updates_only | default(omit) }}'
    exclude: '{{ yum_exclude_packages | default("") | join(",") or omit }}'

- name: Check if reboot is required
  command: "/usr/bin/needs-restarting -r"
  register: reboot_needed
  ignore_errors: true
  failed_when: reboot_needed.rc >= 2
  changed_when: reboot_needed.rc == 1

- name: Restart host and wait for it to get online
  reboot:
  when:
    - reboot_needed is changed
    - reboot_when is undefined or
      reboot_when == 'immediately' 

- name: Schedule a reboot of the system later
  at:
    command: reboot
    count: "{{ reboot_when }}"
    units: minutes
    unique: yes
  when:
    - reboot_needed is changed
    - reboot_when is number

